In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [2]:
train = pd.read_csv("train.csv")
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
train.shape

(1460, 81)

In [4]:
#this will check for the amount of nulls
nulls = train.isna().sum()[train.isna().sum() > 200]
nulls

LotFrontage     259
Alley          1369
FireplaceQu     690
PoolQC         1453
Fence          1179
MiscFeature    1406
dtype: int64

In [5]:
train_cols = list(train.nunique()[train.nunique() < len(train) / 5].index)

In [6]:
train_cols

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'LowQualFinSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition']

In [7]:
train_cat = train.filter(items=train_cols)

In [8]:
train_num = train.filter(items=list(set(train.columns) - set(train_cols)))

In [9]:
train_num.fillna(value = 0, inplace = True)

In [10]:
train_num.isna().any()

GrLivArea      False
Id             False
MasVnrArea     False
LotArea        False
BsmtUnfSF      False
2ndFlrSF       False
TotalBsmtSF    False
SalePrice      False
1stFlrSF       False
BsmtFinSF1     False
GarageArea     False
dtype: bool

In [11]:
X_num = train_num.drop(columns = 'SalePrice', axis = 1)
y_num = train_num.SalePrice

In [12]:
linearmodel1 = LinearRegression()

In [13]:
count = 0
for i in range(0, 1460):
    X_num_train, X_num_test, y_num_train, y_num_test = train_test_split(X_num, y_num, test_size = .2) 
    linearmodel1.fit(X_num_train, y_num_train)
    count = count + linearmodel1.score(X_num_test, y_num_test)
print(count/1460)

0.6494100920222808

In [14]:
tra = preprocessing.LabelEncoder()

train.MSZoning= tra.fit_transform(train.MSZoning)
train.Street= tra.fit_transform(train.Street)
train.LotShape= tra.fit_transform(train.LotShape)
train.LandContour= tra.fit_transform(train.LandContour)
train.Utilities= tra.fit_transform(train.Utilities)
train.LotConfig= tra.fit_transform(train.LotConfig)
train.LandSlope= tra.fit_transform(train.LandSlope)
train.Neighborhood= tra.fit_transform(train.Neighborhood)
train.Condition1= tra.fit_transform(train.Condition1)
train.Condition2= tra.fit_transform(train.Condition2)
train.BldgType= tra.fit_transform(train.BldgType)
train.HouseStyle= tra.fit_transform(train.HouseStyle)
train.OverallQual= tra.fit_transform(train.OverallQual)
train.RoofStyle= tra.fit_transform(train.RoofStyle)
train.RoofMatl= tra.fit_transform(train.RoofMatl)
train.Exterior1st= tra.fit_transform(train.Exterior1st)
train.Exterior2nd= tra.fit_transform(train.Exterior2nd)
train.ExterQual= tra.fit_transform(train.ExterQual)
train.ExterCond= tra.fit_transform(train.ExterCond)
train.Foundation= tra.fit_transform(train.Foundation)
train.Heating= tra.fit_transform(train.Heating)
train.HeatingQC= tra.fit_transform(train.HeatingQC)
train.CentralAir= tra.fit_transform(train.CentralAir)
train.Functional= tra.fit_transform(train.Functional)
train.PavedDrive= tra.fit_transform(train.PavedDrive)
train.SaleType= tra.fit_transform(train.SaleType)
train.SaleCondition= tra.fit_transform(train.SaleCondition)
train.dropna(axis=1,inplace = True)

train

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,8450,1,3,3,0,4,0,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,9600,1,3,3,0,2,0,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,11250,1,0,3,0,4,0,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,9550,1,0,3,0,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,14260,1,0,3,0,2,0,...,0,0,0,0,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,7917,1,3,3,0,4,0,...,0,0,0,0,0,8,2007,8,4,175000
1456,1457,20,3,13175,1,3,3,0,4,0,...,0,0,0,0,0,2,2010,8,4,210000
1457,1458,70,3,9042,1,3,3,0,4,0,...,0,0,0,0,2500,5,2010,8,4,266500
1458,1459,20,3,9717,1,3,3,0,4,0,...,112,0,0,0,0,4,2010,8,4,142125
1459,1460,20,3,9937,1,3,3,0,4,0,...,0,0,0,0,0,6,2008,8,4,147500

In [15]:
X = train.drop('SalePrice',axis = 1)
y = train.SalePrice

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state = 42)

In [16]:
X1_train = X_train[['Neighborhood', 'Condition1', 'Condition2', 'GrLivArea', 'OverallCond', 'YearBuilt',
                  'Functional','LotArea','ExterQual','ExterCond']]

X1_test = X_test[['Neighborhood', 'Condition1', 'Condition2', 'GrLivArea', 'OverallCond', 'YearBuilt',
                  'Functional','LotArea','ExterQual','ExterCond']]

y1_train = y_train

y1_test = y_test

In [17]:
linearmodel2 = LinearRegression().fit(X1_train,y1_train)

In [18]:
coeff = linearmodel2.score(X1_train, y1_train)
print('linearmodel2:', coeff)

linearmodel2: 0.7228464978369695

In [19]:
train = pd.read_csv("train.csv")
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [20]:
threshold = 1000
train = train.drop(list(train.isna().sum()[train.isna().sum() > threshold].index), axis=1)

In [21]:
X = train.drop(['SalePrice'], axis=1)
y = train['SalePrice']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
train_data = X_train.copy()
train_data['SalePrice'] = y_train
train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1063,1064,30,RM,50.0,6000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2006,WD,Normal,110500
187,188,50,RL,60.0,10410,Pave,Reg,Lvl,AllPub,Inside,...,0,140,0,0,0,8,2009,WD,Normal,135000
732,733,60,RL,75.0,11404,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2008,WD,Normal,222500
1247,1248,80,RL,NaN,12328,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2010,WD,Normal,169900
1271,1272,20,RL,NaN,9156,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2009,WD,Normal,185750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,452,20,RL,62.0,70761,Pave,IR1,Low,AllPub,Inside,...,0,0,0,0,0,12,2006,WD,Normal,280000
1180,1181,60,RL,NaN,11170,Pave,IR2,Lvl,AllPub,Corner,...,0,0,0,0,0,4,2006,WD,Normal,250000
465,466,120,RM,NaN,3072,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2006,WD,Normal,178740
126,127,120,RL,NaN,4928,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2007,WD,Normal,128000
925,926,20,RL,NaN,15611,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,3,2008,WD,Abnorml,175000

In [24]:
cor_threshold = train_data.corr()['SalePrice'].median() - 0.1
features = list(train_data.corr()[np.abs(train_data.corr()['SalePrice']) > cor_threshold]['SalePrice'].index)
features.remove('SalePrice')

features

['LotFrontage',
 'LotArea',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'BsmtFullBath',
 'FullBath',
 'HalfBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF']

In [25]:
X_train = X_train[features]
X_test = X_test[features]

In [26]:
X_train = X_train.dropna()
X_test = X_test.dropna()

In [27]:
def drop_IDS(X, y):
    drop = []
    for y_id in y.index:
        if y_id not in X.index:
            drop.append(y_id)
    return drop

In [28]:
y_train = y_train.drop(drop_IDS(X_train, y_train))
y_test = y_test.drop(drop_IDS(X_test, y_test))

In [29]:
pipeline1 = Pipeline([
    ('scalar', StandardScaler()),
    ('linear', LinearRegression(positive=True))
])
pipeline1.fit(X_train, y_train)

Pipeline(steps=[('scalar', StandardScaler()),
                ('linear', LinearRegression(positive=True))])

In [30]:
pipeline1.score(X_test, y_test)

0.8742777740070017